name: Laravel Web Scraper CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          
      - name: Copy .env Example
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Up SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/database/database.sqlite" >> .env

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test

      - name: Run Web Scraper
        run: php artisan app:scrape
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          
      - name: Upload Output File (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: output.json
          path: storage/app/output.json
